# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [24]:
import torch

In [25]:
# Create random tensor

t1= torch.randn(7,7);
print(t1)

tensor([[-2.4671,  0.4248, -1.2529,  0.4309, -0.9580, -0.8318,  0.1962],
        [-0.0252, -1.1707, -0.2834, -1.3214, -0.9780, -0.1360, -1.6783],
        [ 2.0703,  0.0820, -1.4860, -0.3452, -1.3623,  0.2400,  0.1002],
        [-1.5199,  0.9977,  0.7741, -1.4258,  0.9582,  0.3677,  0.2026],
        [ 1.0546,  1.7548,  1.8139,  1.3542, -1.4830,  1.0180, -1.1450],
        [-0.4791, -0.5430, -0.6630,  1.1805, -1.2366,  0.4431,  0.3511],
        [ 1.6226, -0.6695, -0.6017,  0.1842, -1.5052,  0.7585,  0.6732]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor

t1 = torch.randn(3, 4)
t2 = torch.randn(4, 5)

# If you need to transpose, do it like this (only if needed)
t2_transposed = t2.transpose(0, 1)  # This changes shape from [4,5] to [5,4]
print(t2_transposed.shape)

# Perform matrix multiplication
result = torch.matmul(t1, t2)  # t1 shape: [3,4], t2 shape: [4,5] -> Result: [3,5]
print(result.shape)  # Output: torch.Size([3, 5])
print(result)



### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [31]:
# Set manual seed
torch.manual_seed(0);

# Create two random tensors
t1= torch.randn(7,4);
t2= torch.randn(4,1);

# Matrix multiply tensors
result=torch.matmul(t1,t2);
print(result)


tensor([[-2.5474],
        [-1.4000],
        [-0.2194],
        [ 0.6654],
        [-0.3328],
        [-2.8274],
        [ 0.5287]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [37]:
# Set random seed on the GPU
print(torch.cuda.is_available())
torch.cuda.manual_seed(1234)
t3=torch.randn(7,1, device='cuda:0');
print(t3)


True
tensor([[-1.6165],
        [ 0.5685],
        [-0.5102],
        [-0.9113],
        [-1.1555],
        [-0.2262],
        [-1.2891]], device='cuda:0')



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [40]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available());

# Create two random tensors on GPU
t4=torch.tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]],device="cuda:0");

t5=torch.tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]],device="cuda:0");

print(t4.device)
print(t4)
print(t5)



True
cuda:0
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [55]:

# Set the manual seed for reproducibility
torch.manual_seed(1234)

# Check if GPU is available
if torch.cuda.is_available():
    # Create two random tensors of shape (2, 3) on the CPU
    t4=torch.tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]);

    t5=torch.tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]);

    # Send tensors to GPU
    t4 = t4.to('cuda')  # Move tensor t1 to GPU
    t5 = t5.to('cuda')  # Move tensor t2 to GPU

    # Print the tensors and their device
    print("Tensor 1:", t4)
    print("Tensor 2:", t5)
    print("t4.device:", t4.device)  # Should show 'cuda:0'
    print("t5.device:", t5.device)  # Should show 'cuda:0'
else:
    print("GPU is not available.")


Tensor 1: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
Tensor 2: tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
t4.device: cuda:0
t5.device: cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [59]:
# Perform matmul on tensor_A and tensor_B

t5_transpose= t5.transpose(0,1)
result=torch.matmul(t4,t5_transpose)
print(result)
print(result.size())


tensor([[0.3647, 0.4709],
        [0.5183, 0.5617]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [61]:
# Find max
print(result.max())
print(result.min())

# Find min


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [62]:
# Find arg max
print(result.argmax())
print(result.argmin())

# Find arg min


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [64]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t6=torch.randn(1,1,1,10)

# Remove single dimensions
t7=t6.reshape(10,)

# Print out tensors and their shapes
print("tensor 6: ",t6)
print("tensor 7: ",t7)
print("shape tensor 6: ",t6.shape)
print("shape tensor 7: ",t7.shape)


tensor 6:  tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])
tensor 7:  tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])
shape tensor 6:  torch.Size([1, 1, 1, 10])
shape tensor 7:  torch.Size([10])
